In [2]:
from data_transformer import DataTransformer
import pandas as pd 
import numpy as np
import tensorflow as tf

2023-05-08 20:22:35.284711: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.10.1


In [3]:
rawdata = pd.read_csv('adult.csv')
cat_cols = [ 'workclass', 'education', 'marital-status', 'occupation', 'relationship', 'race', 'gender', 'native-country', 'income']
log_cols = []
mixed_cols= {'capital-loss':[0.0],'capital-gain':[0.0]}
num_cols = ['age', 'fnlwgt','educational-num','hours-per-week']
target_col = 'income'


In [4]:
transformer = DataTransformer(rawdata, cat_cols, num_cols,mixed_cols, log_cols, target_col)

In [5]:
#preprocess data
df = transformer.transformData()

In [6]:
df

age    workclass  fnlwgt  education  educational-num  \
37886   28      Private  100829  Bachelors               13   
24949   27      Private   81540    HS-grad                9   
24629   51      Private  123703    HS-grad                9   
25783   33      Private  255334  Bachelors               13   
34688   32      Private  257043    HS-grad                9   
...    ...          ...     ...        ...              ...   
16040   40    Local-gov   36296  Bachelors               13   
5882    27      Private  135296  Bachelors               13   
20602   32      Private   80058    HS-grad                9   
42656   30            ?  201196       11th                7   
280     35  Federal-gov  413930    HS-grad                9   

           marital-status         occupation   relationship   race  gender  \
37886  Married-civ-spouse    Exec-managerial           Wife  White  Female   
24949  Married-civ-spouse       Craft-repair        Husband  White    Male   
24629  Married-civ-spouse  Machine-op-inspct        Husband  White    Male   
25783  Married-civ-spouse     Prof-specialty        Husband  White    Male   
34688       Never-married       Adm-clerical  Not-in-family  White  Female   
...                   ...                ...            ...    ...     ...   
16040  Married-civ-spouse     Prof-specialty        Husband  White    Male   
5882   Married-civ-spouse    Exec-managerial           Wife  White  Female   
20602  Married-civ-spouse       Adm-clerical        Husband  White    Male   
42656       Never-married                  ?      Own-child  Black  Female   
280    Married-civ-spouse       Craft-repair        Husband  White    Male   

       capital-gain  capital-loss  hours-per-week native-country income  
37886             0             0              50  United-States   >50K  
24949             0             0              40  United-States   >50K  
24629          4386             0              40  United-States   >50K  
25783             0             0              25  United-States   >50K  
34688             0             0              42  United-States  <=50K  
...             ...           ...             ...            ...    ...  
16040             0             0              50  United-States   >50K  
5882              0             0              40  United-States   >50K  
20602             0             0              40  United-States  <=50K  
42656             0             0              40  United-States  <=50K  
280               0             0              40  United-States   >50K  

[43957 rows x 15 columns]

In [7]:
transformer.fit(df)

In [8]:
transformed_data = transformer.transform(df)

In [9]:
transformed_data

array([[ 0.06621756,  0.        ,  0.        , ...,  0.        ,
         1.        ,  0.        ],
       [-0.00379732,  0.        ,  0.        , ...,  0.        ,
         1.        ,  0.        ],
       [-0.00945845,  0.        ,  1.        , ...,  0.        ,
         1.        ,  0.        ],
       ...,
       [ 0.34627709,  0.        ,  0.        , ...,  0.        ,
         0.        ,  1.        ],
       [ 0.20624733,  0.        ,  0.        , ...,  0.        ,
         0.        ,  1.        ],
       [ 0.05213279,  0.        ,  0.        , ...,  0.        ,
         1.        ,  0.        ]])

In [10]:
transformed_data.shape

(43957, 164)

In [12]:
#transformer.inverse_transform(transformed_df)

In [11]:
output_info = transformer.output_info_list

In [12]:
output_info

[[SpanInfo(dim=1, activation_fn='tanh'),
  SpanInfo(dim=10, activation_fn='softmax')],
 [SpanInfo(dim=9, activation_fn='softmax')],
 [SpanInfo(dim=1, activation_fn='tanh'),
  SpanInfo(dim=9, activation_fn='softmax')],
 [SpanInfo(dim=16, activation_fn='softmax')],
 [SpanInfo(dim=1, activation_fn='tanh'),
  SpanInfo(dim=10, activation_fn='softmax')],
 [SpanInfo(dim=7, activation_fn='softmax')],
 [SpanInfo(dim=15, activation_fn='softmax')],
 [SpanInfo(dim=6, activation_fn='softmax')],
 [SpanInfo(dim=5, activation_fn='softmax')],
 [SpanInfo(dim=2, activation_fn='softmax')],
 [SpanInfo(dim=1, activation_fn='tanh'),
  SpanInfo(dim=6, activation_fn='softmax')],
 [SpanInfo(dim=1, activation_fn='tanh'),
  SpanInfo(dim=9, activation_fn='softmax')],
 [SpanInfo(dim=1, activation_fn='tanh'),
  SpanInfo(dim=10, activation_fn='softmax')],
 [SpanInfo(dim=42, activation_fn='softmax')],
 [SpanInfo(dim=2, activation_fn='softmax')]]

In [13]:
data = transformed_data

In [14]:
from data_sampler import DataSampler
sampler = DataSampler(data, output_info)

In [15]:
vec, mask, idx, opt1prime = sampler.sample_condvec_train(batch=5)

In [16]:
vec

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,

In [17]:
mask.shape

(5, 15)

In [18]:
mask

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]],
      dtype=float32)

In [19]:
#id of sampled column
idx

array([14,  8,  5,  2,  2])

In [20]:
#id of chosen category in the sampled column
opt1prime

array([0, 1, 2, 4, 6])

In [22]:
import tensorflow as tf
def cross_entropy_conditional_loss(data, convec, mask, output_info):
    """
    Used to compute the conditional loss for ensuring the generator produces the desired category as specified by the conditional vector
    Inputs:
    1) data -> raw data synthesized by the generator 
    2) output_info -> column informtion corresponding to the data transformer
    3) convec -> conditional vectors used to synthesize a batch of data
    4) mask -> a matrix to identify chosen one-hot-encodings across the batch
    Outputs:
    1) loss -> conditional loss corresponding to the generated batch 
    """
    tmp_loss = []
    st = 0
    st_c = 0
    output_info_flat = [elem for sublist in output_info for elem in sublist]
    for column_info in output_info_flat:
        if column_info.activation_fn == 'tanh':
            st += column_info.dim
            continue
        elif column_info.activation_fn == 'softmax':
            ed = st + column_info.dim
            ed_c = st_c + column_info.dim
            logits = data[:, st:ed]
            labels = convec[:, st_c:ed_c]
            tmp = tf.nn.softmax_cross_entropy_with_logits(labels, logits)
            tmp_loss.append(tmp)
            st = ed
            st_c = ed_c
    tmp_loss = tf.stack(tmp_loss, axis=1)
    loss = tf.reduce_mean(tmp_loss * mask)  
    return loss      

In [23]:
with tf.device('/gpu:0'):
    cross_entropy_conditional_loss(data[:5], vec, mask, output_info)

2023-05-08 20:23:46.127085: I tensorflow/compiler/jit/xla_cpu_device.cc:41] Not creating XLA devices, tf_xla_enable_xla_devices not set
2023-05-08 20:23:46.129904: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcuda.so.1
2023-05-08 20:23:46.158494: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1720] Found device 0 with properties: 
pciBusID: 0000:3b:00.0 name: Quadro RTX 8000 computeCapability: 7.5
coreClock: 1.77GHz coreCount: 72 deviceMemorySize: 47.45GiB deviceMemoryBandwidth: 625.94GiB/s
2023-05-08 20:23:46.158850: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1720] Found device 1 with properties: 
pciBusID: 0000:af:00.0 name: Quadro RTX 8000 computeCapability: 7.5
coreClock: 1.77GHz coreCount: 72 deviceMemorySize: 47.45GiB deviceMemoryBandwidth: 625.94GiB/s
2023-05-08 20:23:46.158890: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.10.1
2023-05-08 20:2

In [24]:
d = sampler.sample_data(5, idx, opt1prime)

In [25]:
d.shape

(5, 164)

In [26]:
# sample_data() function in data_sampler.py
# sample the transformed real data according to the conditional vector 
# data -> real transformed input data
# _rid_by_cat_cols is a list of lists - >if we have 15 columns with one-hot code representation, we have 15 lists in _rid_by_cat_cols, each of these 15 lists are list of lists.
# -> the number of these lists is equal to the length of one-hot encoded representation of that column. , the length of these lists are different, for example, the 
# i'th list contains the row index which the i'th element of the one-hot encoding representation is equal to 1. 
# in real data that is equal to 
data = transformed_data
_rid_by_cat_cols = []
n = len(data)
st = 0
output_info_flat = [elem for sublist in output_info for elem in sublist]
for column_info in output_info_flat:
    if column_info.activation_fn == 'tanh':
        st += column_info.dim
        continue
    elif column_info.activation_fn == 'softmax':
        ed = st + column_info.dim
        rid_by_cat = []
        for j in range(column_info.dim):
            rid_by_cat.append(np.nonzero(data[:, st + j])[0])
        _rid_by_cat_cols.append(rid_by_cat)
        st = ed

In [27]:
len(_rid_by_cat_cols)

15

In [28]:
ids = []
for c, o in zip(idx, opt1prime):
    ids.append(np.random.choice(_rid_by_cat_cols[c][o]))


In [29]:
ids

[7217, 5386, 3911, 14905, 35221]

In [30]:
df.columns.get_loc(target_col)

14

In [31]:
output_info

[[SpanInfo(dim=1, activation_fn='tanh'),
  SpanInfo(dim=10, activation_fn='softmax')],
 [SpanInfo(dim=9, activation_fn='softmax')],
 [SpanInfo(dim=1, activation_fn='tanh'),
  SpanInfo(dim=9, activation_fn='softmax')],
 [SpanInfo(dim=16, activation_fn='softmax')],
 [SpanInfo(dim=1, activation_fn='tanh'),
  SpanInfo(dim=10, activation_fn='softmax')],
 [SpanInfo(dim=7, activation_fn='softmax')],
 [SpanInfo(dim=15, activation_fn='softmax')],
 [SpanInfo(dim=6, activation_fn='softmax')],
 [SpanInfo(dim=5, activation_fn='softmax')],
 [SpanInfo(dim=2, activation_fn='softmax')],
 [SpanInfo(dim=1, activation_fn='tanh'),
  SpanInfo(dim=6, activation_fn='softmax')],
 [SpanInfo(dim=1, activation_fn='tanh'),
  SpanInfo(dim=9, activation_fn='softmax')],
 [SpanInfo(dim=1, activation_fn='tanh'),
  SpanInfo(dim=10, activation_fn='softmax')],
 [SpanInfo(dim=42, activation_fn='softmax')],
 [SpanInfo(dim=2, activation_fn='softmax')]]

## make classifier

In [32]:
target_col = 'relationship'
df[target_col].nunique()

6

In [33]:
def get_st_ed(target_col, output_info):
    """
    Used to obtain the start and ending positions of the target column as per the transformed data to be used by the classifier 
    Inputs:
    1) target_col -> name of the target column used for machine learning tasks (binary/multi-classification) in the raw data 
    2) output_info -> column information corresponding to the data after applying the data transformer
    Outputs:
    1) starting (st) and ending (ed) positions of the target column as per the transformed data

    """
    target_col_index = df.columns.get_loc(target_col)
    st = 0
    c = 0
    length = 0
    for info in output_info:
        if c==target_col_index:
            target_info = info
            break
        for item in info:
            st += item.dim
        c += 1
    for item in target_info:
        length += item.dim
    ed = st + length 
    return(st, ed)

In [34]:
st_ed = get_st_ed(target_col, output_info)

In [35]:
#get the dimension of transformed data
output_info = transformer.output_info_list
input_dim = 0
for info in output_info:
    for item in info:
        input_dim += item.dim

In [36]:
input_dim

164

In [37]:
#dimension of input to classifier
dim = input_dim - (st_ed[1] - st_ed[0])
dim

158

In [38]:
import math
class Dense(tf.keras.layers.Layer):
  def __init__(self, input_dim, output_dim):
     super(Dense, self).__init__()
     bound = 1/math.sqrt(input_dim)
     w_init = tf.keras.initializers.RandomUniform(minval=-bound, maxval=bound)
     self.w = tf.Variable(
            initial_value=w_init(shape=(input_dim, output_dim), dtype="float32"),
            trainable=True,
        )
     b_init = tf.keras.initializers.RandomUniform(minval=-bound, maxval=bound)
     self.b = tf.Variable(
            initial_value=b_init(shape=(output_dim,), dtype="float32"), trainable=True
        )
  def call(self,inputs):
      return tf.matmul(inputs, self.w) + self.b


In [39]:
#make classifier
class_dim=(100, 200, 300, 400)

In [40]:
inp_classifier = tf.keras.layers.Input(shape=(dim,))
input_dim = dim
x = inp_classifier
for output_dim in class_dim:
    x = Dense(input_dim, output_dim)(x)
    x = tf.keras.layers.LeakyReLU(alpha=0.2)(x)
    x = tf.keras.layers.Dropout(0.5)(x)
    input_dim = output_dim
input_to_last_layer = output_dim
# in case of binary classification the last layer outputs a single numeric value which is squashed to a probability with sigmoid
if (st_ed[1] - st_ed[0]) == 2:
    x = Dense(input_to_last_layer, 1)(x)
    out = tf.keras.activations.sigmoid(x)
# in case of multi-classs classification, the last layer outputs an array of numeric values associated to each class   
else:
    out = Dense(input_to_last_layer, st_ed[1] - st_ed[0])(x)
classifier = tf.keras.models.Model(inp_classifier, out)
classifier.summary()

Model: "model"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         [(None, 158)]             0         
_________________________________________________________________
dense (Dense)                (None, 100)               15900     
_________________________________________________________________
leaky_re_lu (LeakyReLU)      (None, 100)               0         
_________________________________________________________________
dropout (Dropout)            (None, 100)               0         
_________________________________________________________________
dense_1 (Dense)              (None, 200)               20200     
_________________________________________________________________
leaky_re_lu_1 (LeakyReLU)    (None, 200)               0         
_________________________________________________________________
dropout_1 (Dropout)          (None, 200)               0     

## make discriminator

In [41]:
from ctabgan import CTABGAN
ctabgan = CTABGAN()
discriminator, discriminator_rep, dside = ctabgan.make_discriminator(sampler, transformer)

In [42]:
sampler.n_opt

158

In [43]:
# obtaining the desired height/width for converting tabular data records to square images for feeding it to discriminator network 		
sides = [4, 8, 16, 24, 32]
data_dim = transformer.output_dimensions		
# the discriminator takes the transformed training data concatenated by the corresponding conditional vectors as input
col_size_d = data_dim + sampler.n_opt
for i in sides:
    if i * i >= col_size_d:
        dside = i
        break

In [44]:
dside

24

In [45]:
#discriminator 
num_channels = 64
layer_dims = [(1, dside), (num_channels, dside // 2)]

while layer_dims[-1][1] > 3 and len(layer_dims) < 4:
    # the number of channels increases by a factor of 2 whereas the height/width decreases by the same factor with each layer
    layer_dims.append((layer_dims[-1][0] * 2, layer_dims[-1][1] // 2))

In [46]:
layer_dims

[(1, 24), (64, 12), (128, 6), (256, 3)]

In [47]:
layer_dims[-1][1]

3

In [48]:
import tensorflow as tf
inp = tf.keras.layers.Input(shape=(dside, dside, 1))
x = inp
for curr in layer_dims[1:]:
    x = tf.keras.layers.Conv2D(filters=curr[0], kernel_size=4, strides=2, padding='same', use_bias=False)(x)
    x = tf.keras.layers.BatchNormalization()(x)
    x = tf.keras.layers.LeakyReLU(alpha=0.2)(x)
feature_rep = x
x = tf.keras.layers.Conv2D(filters=1, kernel_size=layer_dims[-1][1], strides=1, padding='valid')(x)
x_flat = tf.keras.layers.Flatten()(x)
out = tf.keras.layers.Dense(1, activation='sigmoid')(x_flat)
discriminator = tf.keras.models.Model(inp, out)
discriminator_rep = tf.keras.models.Model(inp, feature_rep)
discriminator.summary()

Model: "model_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_3 (InputLayer)         [(None, 24, 24, 1)]       0         
_________________________________________________________________
conv2d (Conv2D)              (None, 12, 12, 64)        1024      
_________________________________________________________________
batch_normalization_3 (Batch (None, 12, 12, 64)        256       
_________________________________________________________________
leaky_re_lu_7 (LeakyReLU)    (None, 12, 12, 64)        0         
_________________________________________________________________
conv2d_1 (Conv2D)            (None, 6, 6, 128)         131072    
_________________________________________________________________
batch_normalization_4 (Batch (None, 6, 6, 128)         512       
_________________________________________________________________
leaky_re_lu_8 (LeakyReLU)    (None, 6, 6, 128)         0   

In [49]:
x_flat.shape[1]

1

## make generator

In [50]:
## input to generator
batch_size = 5
random_dim = 100
# Sampling noise vectors using a standard normal distribution
noisez = tf.random.normal([batch_size, random_dim])
#sampling conditional vector
vec, mask, idx, opt1prime = sampler.sample_condvec_train(batch_size)
vec = tf.convert_to_tensor(vec, dtype=tf.float32)
mask = tf.convert_to_tensor(mask, dtype=tf.float32)
# Concatenating conditional vectors and converting resulting noise vectors into the image domain to be fed to the generator as input
noisez = tf.concat([noisez, vec], axis=1)
noisez = tf.reshape(noisez, [batch_size, 1, 1, random_dim + sampler.n_opt])


In [51]:

# obtaining the desired height/width for generating square images from the generator network that can be converted back to tabular domain 
data_dim = transformer.output_dimensions		
sides = [4, 8, 16, 24, 32]
col_size_g = data_dim
for i in sides:
    if i * i >= col_size_g:
        gside = i
        break

num_channels = 64
#num_channels=
# computing the dimensionality of hidden layers
layer_dims = [(1, gside), (num_channels, gside // 2)]

while layer_dims[-1][1] > 3 and len(layer_dims) < 4:
    layer_dims.append((layer_dims[-1][0] * 2, layer_dims[-1][1] // 2))

In [52]:
data_dim

164

In [53]:
layer_dims

[(1, 16), (64, 8), (128, 4), (256, 2)]

In [54]:
 layer_dims[-1][0], layer_dims[-1][1]

(256, 2)

In [55]:
for prev, curr in zip(reversed(layer_dims), reversed(layer_dims[:-1])):
    print(prev[0], curr[0])

256 128
128 64
64 1


In [56]:
inp = tf.keras.layers.Input(shape=(1,1, random_dim + sampler.n_opt))
x = tf.keras.layers.Conv2DTranspose(filters=256, kernel_size=2, strides=1, padding='valid', use_bias=False)(inp)
x = tf.keras.layers.BatchNormalization()(x)
x = tf.keras.layers.ReLU()(x)
x = tf.keras.layers.Conv2DTranspose(filters=128, kernel_size=4, strides=2, padding='same', use_bias=True)(x)
x = tf.keras.layers.BatchNormalization()(x)
x = tf.keras.layers.ReLU()(x)
x = tf.keras.layers.Conv2DTranspose(filters=64, kernel_size=4, strides=2, padding='same', use_bias=True)(x)
x = tf.keras.layers.BatchNormalization()(x)
x = tf.keras.layers.ReLU()(x)
out = tf.keras.layers.Conv2DTranspose(filters=1, kernel_size=4, strides=2, padding='same', use_bias=True)(x)
generator = tf.keras.models.Model(inp, out)

In [57]:
generator.summary()

Model: "model_5"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_4 (InputLayer)         [(None, 1, 1, 258)]       0         
_________________________________________________________________
conv2d_transpose (Conv2DTran (None, 2, 2, 256)         264192    
_________________________________________________________________
batch_normalization_6 (Batch (None, 2, 2, 256)         1024      
_________________________________________________________________
re_lu (ReLU)                 (None, 2, 2, 256)         0         
_________________________________________________________________
conv2d_transpose_1 (Conv2DTr (None, 4, 4, 128)         524416    
_________________________________________________________________
batch_normalization_7 (Batch (None, 4, 4, 128)         512       
_________________________________________________________________
re_lu_1 (ReLU)               (None, 4, 4, 128)         0   

In [56]:
# other way of constructing generator
inp = tf.keras.layers.Input(shape=(1,1, random_dim + sampler.n_opt))
x = tf.keras.layers.Conv2DTranspose(filters=layer_dims[-1][0], kernel_size=layer_dims[-1][1], strides=1, padding='valid', use_bias=False)(inp)
for curr in reversed(layer_dims[:-1]):
    x = tf.keras.layers.BatchNormalization()(x)
    x = tf.keras.layers.ReLU()(x)
    x = tf.keras.layers.Conv2DTranspose(filters=curr[0], kernel_size=4, strides=2, padding='same', use_bias=True)(x)
generator = tf.keras.models.Model(inp, x)
generator.summary()

Model: "model_6"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_5 (InputLayer)         [(None, 1, 1, 258)]       0         
_________________________________________________________________
conv2d_transpose_4 (Conv2DTr (None, 2, 2, 256)         264192    
_________________________________________________________________
batch_normalization_9 (Batch (None, 2, 2, 256)         1024      
_________________________________________________________________
re_lu_3 (ReLU)               (None, 2, 2, 256)         0         
_________________________________________________________________
conv2d_transpose_5 (Conv2DTr (None, 4, 4, 128)         524416    
_________________________________________________________________
batch_normalization_10 (Batc (None, 4, 4, 128)         512       
_________________________________________________________________
re_lu_4 (ReLU)               (None, 4, 4, 128)         0   

In [58]:
with tf.device('/gpu:0'):
    fake = generator(noisez)

2023-05-08 20:27:24.206811: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcublas.so.10
2023-05-08 20:27:24.423901: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudnn.so.7


In [59]:
fake.shape

TensorShape([5, 16, 16, 1])

In [60]:
faket = tf.reshape(fake, (-1, gside * gside))

In [61]:
faket.shape

TensorShape([5, 256])

In [63]:
## sample real data
# Sampling real data according to the conditional vectors and shuffling it before feeding to discriminator to isolate conditional loss on generator
perm = np.arange(batch_size)
np.random.shuffle(perm)
real = sampler.sample_data(batch_size, idx[perm], opt1prime[perm])
real = tf.convert_to_tensor(real.astype('float32'))

# Storing shuffled ordering of the conditional vectors
vec_perm = tf.gather(vec, perm)
real.shape

TensorShape([5, 164])

In [64]:
import tensorflow_probability as tfp
def _gumbel_softmax(logits, tau=1.0, hard=False, dim=-1):
        """Samples from the Gumbel-Softmax distribution
        :cite:`maddison2016concrete`, :cite:`jang2016categorical` and
        optionally discretizes.
        Parameters
        ----------
        logits: tf.Tensor
            Un-normalized log probabilities.
        tau: float, default=1.0
            Non-negative scalar temperature.
        hard: bool, default=False
            If ``True``, the returned samples will be discretized as
            one-hot vectors, but will be differentiated as soft samples.
        dim: int, default=1
            The dimension along which softmax will be computed.
        Returns
        -------
        tf.Tensor
            Sampled tensor of same shape as ``logits`` from the
            Gumbel-Softmax distribution. If ``hard=True``, the returned samples
            will be one-hot, otherwise they will be probability distributions
            that sum to 1 across ``dim``.
        """

        gumbel_dist = tfp.distributions.Gumbel(loc=0, scale=1)
        gumbels = gumbel_dist.sample(tf.shape(logits))
        gumbels = (logits + gumbels) / tau
        output = tf.nn.softmax(gumbels, dim)

        if hard:
            index = tf.math.reduce_max(output, 1, keepdims=True)
            output_hard = tf.cast(tf.equal(output, index), output.dtype)
            output = tf.stop_gradient(output_hard - output) + output
        return output
        

In [66]:
## applying final activation on the generated data (i.e., tanh for numeric and gumbel-softmax for categorical)
data = faket
data_t = []
st = 0
for column_info in output_info:
    for span_info in column_info:
        if span_info.activation_fn == 'tanh':
            ed = st + span_info.dim
            data_t.append(tf.math.tanh(data[:, st:ed]))
            st = ed
        elif span_info.activation_fn == 'softmax':
            ed = st + span_info.dim
            transformed = _gumbel_softmax(data[:, st:ed], tau=0.2)
            data_t.append(transformed)
            st = ed
        else:
            raise ValueError(f'Unexpected activation function {span_info.activation_fn}.')

fakeact = tf.concat(data_t, axis=1)
fakeact.shape

TensorShape([5, 164])

In [67]:
# the generated data is then concatenated with the corresponding condition vectors
fake_cat = tf.concat([fakeact, vec], axis=1)
# the real data is also similarly concatenated with corresponding conditional vectors   
real_cat = tf.concat([real, vec_perm], axis=1)

In [68]:
fake_cat.shape, real_cat.shape

(TensorShape([5, 322]), TensorShape([5, 322]))

: 

In [62]:
# transforming the real and synthetic data into the image domain for feeding it to the discriminator
def transform(dside, data):
    if dside * dside > len(data[0]):
        # Tabular data records are padded with 0 to conform to square shaped images
        padding = tf.zeros((len(data), dside * dside - len(data[0])), dtype=data.dtype)
        data = tf.concat([data, padding], axis=1)

    reshaped_data = tf.reshape(data, (-1, dside, dside, 1))
    return reshaped_data

In [63]:
# transforming the real and synthetic data into the image domain for feeding it to the discriminator
real_cat_d = transform(dside, real_cat)
fake_cat_d = transform(dside, fake_cat)

In [64]:
with tf.device('/gpu:0'):
     # computing the probability of the discriminator to correctly classify real samples hence y_real should ideally be close to 1
     y_real = discriminator(real_cat_d)
     # computing the probability of the discriminator to correctly classify fake samples hence y_fake should ideally be close to 0
     y_fake = discriminator(fake_cat_d)

In [65]:
y_fake

<tf.Tensor: shape=(5, 1), dtype=float32, numpy=
array([[0.49994826],
       [0.5011007 ],
       [0.5017541 ],
       [0.49986437],
       [0.50209063]], dtype=float32)>

In [66]:
# we added a small value of 1e-4 to prevent taking the logarithm of zero, which could cause numerical instability
y_real = y_real + 1e-4
y_fake = y_fake + 1e-4

In [67]:
loss_D_real = tf.keras.losses.binary_crossentropy(tf.ones_like(y_real), y_real)
loss_D_fake = tf.keras.losses.binary_crossentropy(tf.zeros_like(y_fake), y_fake)
disc_loss = loss_D_real + loss_D_fake

In [68]:
#sample noise vector and conditional vector
## input to generator(this time for training generator)
batch_size = 5
random_dim = 100
# Sampling noise vectors using a standard normal distribution
noisez = tf.random.normal([batch_size, random_dim])
#sampling conditional vector
vec, mask, idx, opt1prime = sampler.sample_condvec_train(batch_size)
vec = tf.convert_to_tensor(vec, dtype=tf.float32)
mask = tf.convert_to_tensor(mask, dtype=tf.float32)
# Concatenating conditional vectors and converting resulting noise vectors into the image domain to be fed to the generator as input
noisez = tf.concat([noisez, vec], axis=1)
noisez = tf.reshape(noisez, [batch_size, 1, 1, random_dim + sampler.n_opt])


In [69]:
fake = generator(noisez)
faket = tf.reshape(fake, (-1, gside * gside))

In [70]:
## applying final activation on the generated data (i.e., tanh for numeric and gumbel-softmax for categorical)
data = faket
data_t = []
st = 0
for column_info in output_info:
    for span_info in column_info:
        if span_info.activation_fn == 'tanh':
            ed = st + span_info.dim
            data_t.append(tf.math.tanh(data[:, st:ed]))
            st = ed
        elif span_info.activation_fn == 'softmax':
            ed = st + span_info.dim
            transformed = _gumbel_softmax(data[:, st:ed], tau=0.2)
            data_t.append(transformed)
            st = ed
        else:
            raise ValueError(f'Unexpected activation function {span_info.activation_fn}.')

fakeact = tf.concat(data_t, axis=1)

In [73]:
# the generated data is then concatenated with the corresponding condition vectors
fake_cat = tf.concat([fakeact, vec], axis=1)
fake_cat = transform(dside, fake_cat)

In [78]:
y_fake = discriminator(fake_cat)

In [79]:
info_fake = discriminator_rep(fake_cat)

In [81]:
real_cat = real_cat_d
info_real = discriminator_rep(real_cat)

In [83]:
# computing the conditional loss to ensure the generator generates data records with the chosen category as per the conditional vector
cross_entropy = cross_entropy_conditional_loss(data, vec, mask, output_info)
cross_entropy

<tf.Tensor: shape=(), dtype=float32, numpy=0.110063314>

In [85]:
gen_loss = tf.keras.losses.binary_crossentropy(tf.ones_like(y_fake), y_fake) #it is equivalent to -tf.math.log(y_fake)
gen_loss

<tf.Tensor: shape=(5,), dtype=float32, numpy=
array([0.69504464, 0.6899556 , 0.69013166, 0.69208086, 0.69000715],
      dtype=float32)>

In [84]:
# computing the loss to train the generator where we want y_fake to be close to 1 to fool the discriminator 
# and cross_entropy to be close to 0 to ensure generator's output matches the conditional vector
gen_loss = tf.keras.losses.binary_crossentropy(tf.ones_like(y_fake), y_fake) + cross_entropy

In [87]:
# Computing the information loss by comparing means and stds of real/fake feature representations extracted from discriminator's penultimate layer
loss_mean = tf.norm(tf.math.reduce_mean(info_fake, axis=0) - tf.math.reduce_mean(info_real, axis=0), ord=1)
loss_std = tf.norm(tf.math.reduce_std(info_fake, axis=0) - tf.math.reduce_std(info_real, axis=0), ord=1)
loss_info = loss_mean + loss_std

In [88]:
loss_mean

<tf.Tensor: shape=(), dtype=float32, numpy=3.9331427>

## train

In [ ]:
#computing gradients
